FROM python:slim

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip install gunicorn

COPY app app
COPY migrations migrations
COPY blog.py config.py ./

ENV FLASK_APP=blog.py

EXPOSE 5000
ENTRYPOINT ["flask run"]