"""Add requirement fields

Revision ID: 0ffb619477da
Revises: 5aee121c94bc
Create Date: 2025-10-30 16:56:30.160029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ffb619477da'
down_revision = '5aee121c94bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    with op.batch_alter_table('requirement_sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement_sets', schema=None) as batch_op:
        batch_op.drop_column('description')

    op.create_table('events',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('university', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('degree_level', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('deadline', sa.DATE(), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('source_url', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
