"""Modified fields of user model

Revision ID: 1581d41be03c
Revises: 0ffb619477da
Create Date: 2025-10-30 17:03:46.370871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1581d41be03c'
down_revision = '0ffb619477da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('degree',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('school',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('cpa',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('cpa',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('school',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('degree',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
