"""adding Gantt chart feature

Revision ID: 92f64dcfb3ee
Revises: 8e2ac97074ad
Create Date: 2025-10-23 23:27:33.316887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f64dcfb3ee'
down_revision = '8e2ac97074ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'start_date',
            sa.Date(),
            nullable=False,
            # Hardcode today's date as the default
            server_default='2025-10-23'
        ))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
