name: Github-test-pipeline
on:
  push:
    branches:
      - main
      - dev

jobs:
  set-environment: #check and set the appropriate environment
    runs-on: ubuntu-latest
    outputs: #export the variable for other jobs to access
      current_env: ${{ steps.set_env.outputs.current_env }}
    steps:
      - name: Check if product
        if: endsWith(github.ref, '/main')
        run: |
          echo "ENVIRONMENT_NAME=prod" >> $GITHUB_ENV
      - name: Check if dev
        if: endsWith(github.ref, '/dev')
        run: |
          echo "ENVIRONMENT_NAME=dev" >> $GITHUB_ENV
      - name: Set the output
        id: set_env
        run: echo "::set-output name=current_env::${{ env.ENVIRONMENT_NAME }}"
  
  build-and-deploy:
      runs-on: ubuntu-latest
      needs: set-environment
      environment: ${{ needs.set-environment.outputs.current_env }}
      steps:
        - name: Get secret
          run: |
            echo "Deloying to ${{ needs.set-environment.outputs.current_env}} environment."
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker buildx
          uses: docker/setup-buildx-action@v3
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: .
            push: false
            tags: user/app:latest